### ISSUE TITLE
Composite prebuilt crashes with an error dialog box.

### ISSUE THREAD

**Issue by joeykleingers** [BlueQuartzSoftware/DREAM3D#623] opened 2017-02-02 15:40 UTC
Composite prebuilt pipeline (Synthetic #5) crashes on launch with an error dialog that reads:

"Internal error gathering statistics from Statistics Widgets. Error code -1000"

This is on Mac OS X Yosemite.

**Comment by imikejackson** [comment] 2017-02-02 15:52
Duplicate of #620

**Closed as completed by imikejackson** 2017-02-02 15:53 UTC
Labels: Bug
