### ISSUE TITLE
dynamic_cast failure

### ISSUE THREAD

**Issue by dzenanz** [BlueQuartzSoftware/DREAM3D#910] opened 2019-08-14 17:38 UTC
`dynamic_cast` can fail when classes cross module boundaries.

As per this [SO answer](https://stackoverflow.com/a/49348235/276168), adding `-flat_namespace` linker flag leads to failure to load `CAxisByPolarizedLightPlugin` (constructor?):
```text
13:05:05: Debugging starts
PipelineRunner SIMPLib Version 2.0.133.0e2471558
Input File: /Users/kitware/Dashboards/matt/DREAM3D/Support/PrebuiltPipelines/Examples/Image_Histogram.json
2019-08-14 13:05:09.992529-0400 PipelineRunner_debug[49264:265753114] Loading SIMPLib Plugins.
2019-08-14 13:05:09.992558-0400 PipelineRunner_debug[49264:265753114] Adding Folder  "/Users/kitware/Dashboards/matt/DREAM3D-Build/Debug/Bin"
2019-08-14 13:05:09.992574-0400 PipelineRunner_debug[49264:265753114]   Adding Path  "/Users/kitware/Dashboards/matt/DREAM3D-Build/Debug/Bin/Plugins"
2019-08-14 13:05:09.992588-0400 PipelineRunner_debug[49264:265753114] SIMPL_PLUGIN_PATH: ""
2019-08-14 13:05:09.992616-0400 PipelineRunner_debug[49264:265753114] Removed  0  duplicate Plugin Paths
2019-08-14 13:05:09.992625-0400 PipelineRunner_debug[49264:265753114] Plugin Directory being Searched:  "/Users/kitware/Dashboards/matt/DREAM3D-Build/Debug/Bin"
2019-08-14 13:05:09.993974-0400 PipelineRunner_debug[49264:265753114] Plugin Directory being Searched:  "/Users/kitware/Dashboards/matt/DREAM3D-Build/Debug/Bin/Plugins"
2019-08-14 13:05:09.994886-0400 PipelineRunner_debug[49264:265753114] Plugin Being Loaded: "/Users/kitware/Dashboards/matt/DREAM3D-Build/Debug/Bin/Plugins/libCAxisByPolarizedLight_debug.plugin"
dyld: lazy symbol binding failed: Symbol not found: __ZN27CAxisByPolarizedLightPluginC1Ev
  Referenced from: /Users/kitware/Dashboards/matt/DREAM3D-Build/Debug/Bin/Plugins/libCAxisByPolarizedLight_debug.plugin
  Expected in: flat namespace

dyld: Symbol not found: __ZN27CAxisByPolarizedLightPluginC1Ev
  Referenced from: /Users/kitware/Dashboards/matt/DREAM3D-Build/Debug/Bin/Plugins/libCAxisByPolarizedLight_debug.plugin
  Expected in: flat namespace

13:05:31: Debugging has finished
```
or
```text
2d [kitware:~/Dashboards/matt/DREAM3D-Build/Debug] 4s 8 $ ctest -VV -R CAxisByPolarizedLightUnitTest
UpdateCTestConfiguration  from :/Users/kitware/Dashboards/matt/DREAM3D-Build/Debug/DartConfiguration.tcl
Parse Config file:/Users/kitware/Dashboards/matt/DREAM3D-Build/Debug/DartConfiguration.tcl
UpdateCTestConfiguration  from :/Users/kitware/Dashboards/matt/DREAM3D-Build/Debug/DartConfiguration.tcl
Parse Config file:/Users/kitware/Dashboards/matt/DREAM3D-Build/Debug/DartConfiguration.tcl
Test project /Users/kitware/Dashboards/matt/DREAM3D-Build/Debug
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 64
    Start 64: CAxisByPolarizedLightUnitTest

64: Test command: /Users/kitware/Dashboards/matt/DREAM3D-Build/Debug/Bin/CAxisByPolarizedLightUnitTest
64: Test timeout computed to be: 1500
64: Loading SIMPLib Plugins.
64: Adding Folder  "/Users/kitware/Dashboards/matt/DREAM3D-Build/Debug/Bin"
64:   Adding Path  "/Users/kitware/Dashboards/matt/DREAM3D-Build/Debug/Bin/Plugins"
64: SIMPL_PLUGIN_PATH: ""
64: Removed  0  duplicate Plugin Paths
64: Plugin Directory being Searched:  "/Users/kitware/Dashboards/matt/DREAM3D-Build/Debug/Bin"
64: Plugin Directory being Searched:  "/Users/kitware/Dashboards/matt/DREAM3D-Build/Debug/Bin/Plugins"
64: Plugin Being Loaded: "/Users/kitware/Dashboards/matt/DREAM3D-Build/Debug/Bin/Plugins/libCAxisByPolarizedLight_debug.plugin"
64: dyld: lazy symbol binding failed: Symbol not found: __ZN27CAxisByPolarizedLightPluginC1Ev
64:   Referenced from: /Users/kitware/Dashboards/matt/DREAM3D-Build/Debug/Bin/Plugins/libCAxisByPolarizedLight_debug.plugin
64:   Expected in: flat namespace
64: 
64: dyld: Symbol not found: __ZN27CAxisByPolarizedLightPluginC1Ev
64:   Referenced from: /Users/kitware/Dashboards/matt/DREAM3D-Build/Debug/Bin/Plugins/libCAxisByPolarizedLight_debug.plugin
64:   Expected in: flat namespace
64: 
1/1 Test #64: CAxisByPolarizedLightUnitTest ....Child aborted***Exception:   0.23 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.24 sec

The following tests FAILED:
	 64 - CAxisByPolarizedLightUnitTest (Child aborted)
Errors while running CTest
```
Could it be that without `-flat_namespace` the constructor is simply not executed?

**Comment by dzenanz** [comment] 2019-08-14 17:39
@thewtex @imikejackson I couldn't find an issue for this, if we already had it.

**Comment by imikejackson** [comment] 2019-08-14 17:42
Interestingly I just fixed an issue with our python bindings that had the same issue of failure to dynamic_pointer_cast() if a DataArray<T> object was constructed in the incorrect library. I also tried compiling with the ```-flat_namespace``` flag but I don't think I got any load errors. I'll try to reproduce on my end.

**Comment by dzenanz** [comment] 2019-08-14 17:51
`nm -mo Bin/Plugins/libCAxisByPolarizedLight_debug.plugin` gives (among other things):
```text
Bin/Plugins/libCAxisByPolarizedLight_debug.plugin: 000000000056dba0 (__TEXT,__text) external __ZN27CAxisByPolarizedLightPluginC1Ev
Bin/Plugins/libCAxisByPolarizedLight_debug.plugin: 000000000056d970 (__TEXT,__text) external __ZN27CAxisByPolarizedLightPluginC2Ev
Bin/Plugins/libCAxisByPolarizedLight_debug.plugin: 000000000056dd00 (__TEXT,__text) external __ZN27CAxisByPolarizedLightPluginD0Ev
Bin/Plugins/libCAxisByPolarizedLight_debug.plugin: 000000000056dcc0 (__TEXT,__text) external __ZN27CAxisByPolarizedLightPluginD1Ev
Bin/Plugins/libCAxisByPolarizedLight_debug.plugin: 000000000056dbc0 (__TEXT,__text) external __ZN27CAxisByPolarizedLightPluginD2Ev
```
whereas `nm -mo Bin/Plugins/libCAxisByPolarizedLightUi_debug.guiplugin` gives:
```text
libCAxisByPolarizedLightUi_debug.guiplugin:                  (undefined) external __ZN27CAxisByPolarizedLightPluginC2Ev
libCAxisByPolarizedLightUi_debug.guiplugin:                  (undefined) external __ZN27CAxisByPolarizedLightPluginD2Ev
```
GUI plugin has only 2 suffix of constructor. I don't know whether this means anything.

**Comment by dzenanz** [comment] 2019-08-14 17:52
@imikejackson I added `-flat_namespace` only to DREAM3D, not all the dependencies. Maybe that matters?

**Comment by imikejackson** [comment] 2019-08-14 18:13
Well, it gives me an idea where to start...

**Comment by dzenanz** [comment] 2019-08-14 18:16
During debugging, `inputArrayPtr` on [line 255](https://github.com/BlueQuartzSoftware/DREAM3D/blob/a5196735036b378ec3a19a3502db3d029dbff0db/Source/Plugins/Statistics/StatisticsFilters/CalculateArrayHistogram.cpp#L255) is `null`, because `inputDataPtr`'s internal array pointer is null.

**Comment by dzenanz** [comment] 2019-08-14 18:19
Meaning, the problem is in properly passing the image/array between DREAM3D filters.

**Comment by imikejackson** [comment] 2019-08-14 18:50
Nope. The problem is something else. I am actually got there through another failure. Something in ITKImageReader isn't quite correct. The array should be allocated and it is not... At least that is what I am seeing..

**Comment by dzenanz** [comment] 2019-08-14 18:52
Well, it could be that too. But the problem doesn't seem to be in `CalculateArrayHistogram`.

**Comment by imikejackson** [comment] 2019-08-14 18:58
Is the pipeline that you are running reading an image to start?

**Comment by dzenanz** [comment] 2019-08-14 19:11
Yes, I was debugging **PipelineRunner** with `DREAM3D/Support/PrebuiltPipelines/Examples/Image_Histogram.json`, and it references `Data/Image/slice_11.tif`.

**Comment by imikejackson** [comment] 2019-08-14 19:14
Hmm. That, it turns out, is exactly what I am doing....

**Comment by imikejackson** [comment] 2019-08-14 20:25
@dzenanz  As a sanity check I changed the plugin loading code to load up the .guiplugin instead of the .plugin files and now the code works fine. So there probably is some sort of dynamic_casting over library boundaries that is giving an issue.

**Comment by imikejackson** [comment] 2019-08-14 20:27
The odd part is that I can run the ImportAxioVisionV4 example pipeline and it works just fine. The ImportAxioVisionV4 filter slaves out to the ITKImageReader filter (but *both* are in ITKImageProcessing plugin) to do the image reading.

**Comment by dzenanz** [comment] 2019-08-15 20:05
These are the types which are involved in failure.
```text
2d [kitware:~/Dashboards/matt/DREAM3D-Build/Debug/Bin] $ nm -mo Plugins/* | grep N3itk12Dream3DImageIhLj2EEE
Plugins/libITKImageProcessing_debug.plugin: 0000000000323080 (__TEXT,__text) weak external __Z25itkDynamicCastInDebugModeIPKN3itk12Dream3DImageIhLj2EEEPKNS0_10DataObjectEET_T0_
Plugins/libITKImageProcessing_debug.plugin: 0000000000331270 (__TEXT,__text) weak external __Z25itkDynamicCastInDebugModeIPN3itk12Dream3DImageIhLj2EEEPNS0_10DataObjectEET_T0_
Plugins/libITKImageProcessing_debug.plugin: 0000000003a2e140 (__TEXT,__text) non-external __ZN12_GLOBAL__N_110WriteDebugIN3itk12Dream3DImageIhLj2EEEEEvPKT_PKc
Plugins/libITKImageProcessing_debug.plugin: 0000000004075040 (__TEXT,__text) weak external __ZN16ITKStitchMontage19convertMontageToD3DIhN3itk12Dream3DImageIhLj2EEEEEvPT0_
Plugins/libITKImageProcessing_debug.plugin: 000000000c75e7c0 (__DATA,__const) weak external __ZTIN3itk12Dream3DImageIhLj2EEE
Plugins/libITKImageProcessing_debug.plugin: 000000000c75ea70 (__DATA,__const) weak external __ZTIPKN3itk12Dream3DImageIhLj2EEE
Plugins/libITKImageProcessing_debug.plugin: 000000000c75ed80 (__DATA,__const) weak external __ZTIPN3itk12Dream3DImageIhLj2EEE
Plugins/libITKImageProcessing_debug.plugin: 000000000bf652b0 (__TEXT,__const) weak external __ZTSN3itk12Dream3DImageIhLj2EEE
Plugins/libITKImageProcessing_debug.plugin: 000000000bf65350 (__TEXT,__const) weak external __ZTSPKN3itk12Dream3DImageIhLj2EEE
Plugins/libITKImageProcessing_debug.plugin: 000000000bf653a0 (__TEXT,__const) weak external __ZTSPN3itk12Dream3DImageIhLj2EEE
Plugins/libITKImageProcessing_debug.plugin: 000000000c8aff50 (__DATA,__const) non-external (was a private external) __ZTVN3itk12Dream3DImageIhLj2EEE
2d [kitware:~/Dashboards/matt/DREAM3D-Build/Debug/Bin] 4s $ nm -mo Plugins/* | grep PN3itk10DataObjectE
Plugins/libCAxisByPolarizedLight_debug.plugin: 000000000061c590 (__DATA,__const) weak external __ZTIPN3itk10DataObjectE
Plugins/libCAxisByPolarizedLight_debug.plugin: 00000000005d78c0 (__TEXT,__const) weak external __ZTSPN3itk10DataObjectE
Plugins/libDREAM3DReview_debug.plugin: 0000000000db1fe0 (__DATA,__const) weak external __ZTIPN3itk10DataObjectE
Plugins/libDREAM3DReview_debug.plugin: 0000000000d63710 (__TEXT,__const) weak external __ZTSPN3itk10DataObjectE
Plugins/libITKImageProcessing_debug.plugin: 000000000c758470 (__DATA,__const) weak external __ZTIPN3itk10DataObjectE
Plugins/libITKImageProcessing_debug.plugin: 000000000bf63b60 (__TEXT,__const) weak external __ZTSPN3itk10DataObjectE
Plugins/libImageProcessing_debug.plugin: 0000000000bb8010 (__DATA,__const) weak external __ZTIPN3itk10DataObjectE
Plugins/libImageProcessing_debug.plugin: 0000000000b1e220 (__TEXT,__const) weak external __ZTSPN3itk10DataObjectE
2d [kitware:~/Dashboards/matt/DREAM3D-Build/Debug/Bin] 5s $ nm -mo Plugins/* | grep PN3itk9ImageBaseILj2EEE
Plugins/libCAxisByPolarizedLight_debug.plugin: 0000000000154630 (__TEXT,__text) weak external __Z25itkDynamicCastInDebugModeIPN3itk9ImageBaseILj2EEEPNS0_10DataObjectEET_T0_
Plugins/libCAxisByPolarizedLight_debug.plugin: 0000000000619580 (__DATA,__const) weak external __ZTIPN3itk9ImageBaseILj2EEE
Plugins/libCAxisByPolarizedLight_debug.plugin: 00000000005d48d0 (__TEXT,__const) weak external __ZTSPN3itk9ImageBaseILj2EEE
Plugins/libDREAM3DReview_debug.plugin: 0000000000b558d0 (__TEXT,__text) weak external __Z25itkDynamicCastInDebugModeIPN3itk9ImageBaseILj2EEEPNS0_10DataObjectEET_T0_
Plugins/libDREAM3DReview_debug.plugin: 0000000000db4230 (__DATA,__const) weak external __ZTIPN3itk9ImageBaseILj2EEE
Plugins/libDREAM3DReview_debug.plugin: 0000000000d63f90 (__TEXT,__const) weak external __ZTSPN3itk9ImageBaseILj2EEE
Plugins/libITKImageProcessing_debug.plugin: 0000000000326e10 (__TEXT,__text) weak external __Z25itkDynamicCastInDebugModeIPN3itk9ImageBaseILj2EEEPNS0_10DataObjectEET_T0_
Plugins/libITKImageProcessing_debug.plugin: 000000000c735aa0 (__DATA,__const) weak external __ZTIPN3itk9ImageBaseILj2EEE
Plugins/libITKImageProcessing_debug.plugin: 000000000bf3c2d0 (__TEXT,__const) weak external __ZTSPN3itk9ImageBaseILj2EEE
Plugins/libImageProcessing_debug.plugin: 00000000000d79d0 (__TEXT,__text) weak external __Z25itkDynamicCastInDebugModeIPN3itk9ImageBaseILj2EEEPNS0_10DataObjectEET_T0_
Plugins/libImageProcessing_debug.plugin: 0000000000bb9e50 (__DATA,__const) weak external __ZTIPN3itk9ImageBaseILj2EEE
Plugins/libImageProcessing_debug.plugin: 0000000000b1c250 (__TEXT,__const) weak external __ZTSPN3itk9ImageBaseILj2EEE
2d [kitware:~/Dashboards/matt/DREAM3D-Build/Debug/Bin] 5s $
```
However I don't know why all of them are multiplied a few times.

But `itk::Dream3DImage` is only known to `Plugins/libITKImageProcessing_debug.plugin`, whereas `itk::ImageBase` and `itk:DataObject` are known to 4 plugins. So probably `ITKImageProcessing` plugin needs to be loaded first, to bring in the ITK code which properly supports `Dream3DImage` assuming the definitions for same classes are incompatible among different plugins due to two-level type checking.

**Comment by dzenanz** [comment] 2019-08-15 20:06
```text
15:34:30: Debugging starts
PipelineRunner SIMPLib Version 2.0.133.0e2471558
Input File: /Users/kitware/Dashboards/matt/DREAM3D/Support/PrebuiltPipelines/Examples/Image_Histogram.json
2019-08-15 15:34:36.283495-0400 PipelineRunner_debug[50485:266459330] Loading SIMPLib Plugins.
2019-08-15 15:34:36.283533-0400 PipelineRunner_debug[50485:266459330] Adding Folder  "/Users/kitware/Dashboards/matt/DREAM3D-Build/Debug/Bin"
2019-08-15 15:34:36.283548-0400 PipelineRunner_debug[50485:266459330]   Adding Path  "/Users/kitware/Dashboards/matt/DREAM3D-Build/Debug/Bin/Plugins"
2019-08-15 15:34:36.283561-0400 PipelineRunner_debug[50485:266459330] SIMPL_PLUGIN_PATH: ""
2019-08-15 15:34:36.283581-0400 PipelineRunner_debug[50485:266459330] Removed  0  duplicate Plugin Paths
2019-08-15 15:34:36.283606-0400 PipelineRunner_debug[50485:266459330] Plugin Directory being Searched:  "/Users/kitware/Dashboards/matt/DREAM3D-Build/Debug/Bin"
2019-08-15 15:34:36.284784-0400 PipelineRunner_debug[50485:266459330] Plugin Directory being Searched:  "/Users/kitware/Dashboards/matt/DREAM3D-Build/Debug/Bin/Plugins"
2019-08-15 15:34:36.285588-0400 PipelineRunner_debug[50485:266459330] Plugin Being Loaded: "/Users/kitware/Dashboards/matt/DREAM3D-Build/Debug/Bin/Plugins/libCAxisByPolarizedLight_debug.plugin"
2019-08-15 15:34:39.723720-0400 PipelineRunner_debug[50485:266459330]     Pointer:  CAxisByPolarizedLightPlugin(0x11183ea20)
2019-08-15 15:34:39.724156-0400 PipelineRunner_debug[50485:266459330] Plugin Being Loaded: "/Users/kitware/Dashboards/matt/DREAM3D-Build/Debug/Bin/Plugins/libDREAM3DReview_debug.plugin"
2019-08-15 15:34:40.392896-0400 PipelineRunner_debug[50485:266459330]     Pointer:  DREAM3DReviewPlugin(0x113b96640)
2019-08-15 15:34:40.400051-0400 PipelineRunner_debug[50485:266459330] Plugin Being Loaded: "/Users/kitware/Dashboards/matt/DREAM3D-Build/Debug/Bin/Plugins/libEMMPM_debug.plugin"
2019-08-15 15:34:40.483361-0400 PipelineRunner_debug[50485:266459330]     Pointer:  EMMPMPlugin(0x113a79cb0)
2019-08-15 15:34:40.484122-0400 PipelineRunner_debug[50485:266459330] Plugin Being Loaded: "/Users/kitware/Dashboards/matt/DREAM3D-Build/Debug/Bin/Plugins/libGeneric_debug.plugin"
2019-08-15 15:34:40.578481-0400 PipelineRunner_debug[50485:266459330]     Pointer:  GenericPlugin(0x113a7ac30)
2019-08-15 15:34:40.579772-0400 PipelineRunner_debug[50485:266459330] Plugin Being Loaded: "/Users/kitware/Dashboards/matt/DREAM3D-Build/Debug/Bin/Plugins/libImageProcessing_debug.plugin"
2019-08-15 15:34:41.268106-0400 PipelineRunner_debug[50485:266459330]     Pointer:  ImageProcessingPlugin(0x105ac5c70)
2019-08-15 15:34:41.269573-0400 PipelineRunner_debug[50485:266459330] Plugin Being Loaded: "/Users/kitware/Dashboards/matt/DREAM3D-Build/Debug/Bin/Plugins/libImportExport_debug.plugin"
2019-08-15 15:34:41.528090-0400 PipelineRunner_debug[50485:266459330]     Pointer:  ImportExportPlugin(0x113ac8600)
2019-08-15 15:34:41.531427-0400 PipelineRunner_debug[50485:266459330] Plugin Being Loaded: "/Users/kitware/Dashboards/matt/DREAM3D-Build/Debug/Bin/Plugins/libITKImageProcessing_debug.plugin"
2019-08-15 15:34:54.782643-0400 PipelineRunner_debug[50485:266459330]     Pointer:  ITKImageProcessingPlugin(0x12f3ecae0)
2019-08-15 15:34:54.797214-0400 PipelineRunner_debug[50485:266459330] Plugin Being Loaded: "/Users/kitware/Dashboards/matt/DREAM3D-Build/Debug/Bin/Plugins/libOrientationAnalysis_debug.plugin"
2019-08-15 15:34:55.970039-0400 PipelineRunner_debug[50485:266459330]     Pointer:  OrientationAnalysisPlugin(0x1318d9750)
2019-08-15 15:34:55.979434-0400 PipelineRunner_debug[50485:266459330] Plugin Being Loaded: "/Users/kitware/Dashboards/matt/DREAM3D-Build/Debug/Bin/Plugins/libProcessing_debug.plugin"
2019-08-15 15:34:56.131643-0400 PipelineRunner_debug[50485:266459330]     Pointer:  ProcessingPlugin(0x131a73c70)
2019-08-15 15:34:56.134001-0400 PipelineRunner_debug[50485:266459330] Plugin Being Loaded: "/Users/kitware/Dashboards/matt/DREAM3D-Build/Debug/Bin/Plugins/libReconstruction_debug.plugin"
2019-08-15 15:34:56.324549-0400 PipelineRunner_debug[50485:266459330]     Pointer:  ReconstructionPlugin(0x1318e1890)2019-08-15 15:34:56.327028-0400 PipelineRunner_debug[50485:266459330] Plugin Being Loaded: "/Users/kitware/Dashboards/matt/DREAM3D-Build/Debug/Bin/Plugins/libSampling_debug.plugin"
2019-08-15 15:34:56.470447-0400 PipelineRunner_debug[50485:266459330]     Pointer:  SamplingPlugin(0x131acb0e0)
2019-08-15 15:34:56.472891-0400 PipelineRunner_debug[50485:266459330] Plugin Being Loaded: "/Users/kitware/Dashboards/matt/DREAM3D-Build/Debug/Bin/Plugins/libSimulationIO_debug.plugin"
2019-08-15 15:34:56.562080-0400 PipelineRunner_debug[50485:266459330]     Pointer:  SimulationIOPlugin(0x131910a80)
2019-08-15 15:34:56.564421-0400 PipelineRunner_debug[50485:266459330] Plugin Being Loaded: "/Users/kitware/Dashboards/matt/DREAM3D-Build/Debug/Bin/Plugins/libStatistics_debug.plugin"
2019-08-15 15:34:56.876472-0400 PipelineRunner_debug[50485:266459330]     Pointer:  StatisticsPlugin(0x131f38970)
2019-08-15 15:34:56.880782-0400 PipelineRunner_debug[50485:266459330] Plugin Being Loaded: "/Users/kitware/Dashboards/matt/DREAM3D-Build/Debug/Bin/Plugins/libSurfaceMeshing_debug.plugin"2019-08-15 15:34:57.463874-0400 PipelineRunner_debug[50485:266459330]     Pointer:  SurfaceMeshingPlugin(0x131f3aea0)
2019-08-15 15:34:57.466654-0400 PipelineRunner_debug[50485:266459330] Plugin Being Loaded: "/Users/kitware/Dashboards/matt/DREAM3D-Build/Debug/Bin/Plugins/libSyntheticBuilding_debug.plugin"
2019-08-15 15:34:57.676476-0400 PipelineRunner_debug[50485:266459330]     Pointer:  SyntheticBuildingPlugin(0x135633c20)
2019-08-15 15:34:57.682046-0400 PipelineRunner_debug[50485:266459330] Plugin Being Loaded: "/Users/kitware/Dashboards/matt/DREAM3D-Build/Debug/Bin/Plugins/libUCSBUtilities_debug.plugin"
2019-08-15 15:34:57.855710-0400 PipelineRunner_debug[50485:266459330]     Pointer:  UCSBUtilitiesPlugin(0x1356e0ea0)
Pipeline Count: 3
WARNING: In /Users/kitware/Dashboards/matt/DREAM3D_SDK/superbuild/ITK/Source/ITK/Modules/IO/TIFF/src/itkTIFFImageIO.cxx, line 1159
TIFFImageIO (0x1356e2610): EXIFIFDOffset has unsupported data type (18) for meta-data dictionary.

WARNING: In /Users/kitware/Dashboards/matt/DREAM3D_SDK/superbuild/ITK/Source/ITK/Modules/IO/TIFF/src/itkTIFFImageIO.cxx, line 1159
TIFFImageIO (0x1356e6cc0): EXIFIFDOffset has unsupported data type (18) for meta-data dictionary.

[1/3] ITK::Image Reader
WARNING: In /Users/kitware/Dashboards/matt/DREAM3D_SDK/superbuild/ITK/Source/ITK/Modules/IO/TIFF/src/itkTIFFImageIO.cxx, line 1159
TIFFImageIO (0x1356e95d0): EXIFIFDOffset has unsupported data type (18) for meta-data dictionary.

WARNING: In /Users/kitware/Dashboards/matt/DREAM3D_SDK/superbuild/ITK/Source/ITK/Modules/IO/TIFF/src/itkTIFFImageIO.cxx, line 1159
TIFFImageIO (0x1356e3140): EXIFIFDOffset has unsupported data type (18) for meta-data dictionary.

WARNING: In /Users/kitware/Dashboards/matt/DREAM3D_SDK/superbuild/ITK/Source/ITK/Modules/IO/TIFF/src/itkTIFFImageIO.cxx, line 1159
TIFFImageIO (0x1356e3140): EXIFIFDOffset has unsupported data type (18) for meta-data dictionary.

WARNING: In /Users/kitware/Dashboards/matt/DREAM3D_SDK/superbuild/ITK/Source/ITK/Modules/IO/TIFF/src/itkTIFFImageIO.cxx, line 1159
TIFFImageIO (0x1356e9420): EXIFIFDOffset has unsupported data type (18) for meta-data dictionary.

ptr: 4872978960 N3itk12Dream3DImageIhLj2EEE
'ITKImageReader' Error (-55557): ITK exception was thrown while processing input file: /Users/kitware/Dashboards/matt/DREAM3D_SDK/superbuild/ITK/Source/ITK/Modules/Core/Common/include/itkMacro.h:1356:
itk::ERROR: Failed dynamic cast to PN3itk9ImageBaseILj2EEE object type = Dream3DImage
Error (-55557): [1/3] ITK::Image Reader caused an error during execution.
```

**Comment by dzenanz** [comment] 2019-08-15 20:16
I confirmed that trouble comes from [this](https://github.com/InsightSoftwareConsortium/ITK/commit/d50d4f91374d1ffa1fae7dbbdcdc775825ffb10c#diff-306d4781e5b6657fff3ba80936b7f38bR207) `dynamic_cast` which was introduced 10 years ago. We cannot replace it by `static_cast` because the output might be something other than `Image`, causing some other things to fail:
```text
        297 - RGBColormapTest_red (SEGFAULT)
        298 - RGBColormapTest_green (SEGFAULT)
        299 - RGBColormapTest_blue (SEGFAULT)
        300 - RGBColormapTest_hot (SEGFAULT)
        301 - RGBColormapTest_cool (SEGFAULT)
        302 - RGBColormapTest_spring (SEGFAULT)
        303 - RGBColormapTest_summer (SEGFAULT)
        304 - RGBColormapTest_autumn (SEGFAULT)
        305 - RGBColormapTest_winter (SEGFAULT)
        306 - RGBColormapTest_copper (SEGFAULT)
        307 - RGBColormapTest_hsv (SEGFAULT)
        308 - RGBColormapTest_jet (SEGFAULT)
        309 - RGBColormapTest_overunder (SEGFAULT)
        667 - itkMaskedFFTNormalizedCorrelationImageFilterTest1 (SEGFAULT)
        668 - itkMaskedFFTNormalizedCorrelationImageFilterTest2 (SEGFAULT)
        669 - itkMaskedFFTNormalizedCorrelationImageFilterTest3 (SEGFAULT)
        670 - itkMaskedFFTNormalizedCorrelationImageFilterTest4 (SEGFAULT)
        671 - itkMaskedFFTNormalizedCorrelationImageFilterTest5 (SEGFAULT)
        672 - itkMaskedFFTNormalizedCorrelationImageFilterTest6 (SEGFAULT)
        673 - itkFFTNormalizedCorrelationImageFilterTest1 (SEGFAULT)
        674 - itkFFTNormalizedCorrelationImageFilterTest2 (SEGFAULT)
        675 - itkFFTNormalizedCorrelationImageFilterTest3 (SEGFAULT)
        676 - itkFFTNormalizedCorrelationImageFilterTest4 (SEGFAULT)
        677 - itkFFTNormalizedCorrelationImageFilterTest5 (SEGFAULT)
        770 - itkFFTWF_FFTTest (SEGFAULT)
        774 - itkFFTWD_FFTTest (SEGFAULT)
        786 - itkFullToHalfHermitianImageFilterTestEvenEven (SEGFAULT)
        787 - itkFullToHalfHermitianImageFilterTestEvenOdd (SEGFAULT)
        788 - itkFullToHalfHermitianImageFilterTestOddEven (SEGFAULT)
        789 - itkFullToHalfHermitianImageFilterTestOddOdd (SEGFAULT)
        790 - itkForwardInverseFFTImageFilterTest1 (SEGFAULT)
        791 - itkForwardInverseFFTImageFilterTest2 (SEGFAULT)
        792 - itkComplexToComplexFFTImageFilter2DFloatTest (SEGFAULT)
        793 - itkComplexToComplexFFTImageFilter3DFloatTest (SEGFAULT)
        794 - itkComplexToComplexFFTImageFilter2DDoubleTest (SEGFAULT)
        795 - itkComplexToComplexFFTImageFilter3DDoubleTest (SEGFAULT)
        796 - itkVnlComplexToComplexFFTImageFilter2DFloatTest (SEGFAULT)
        797 - itkVnlComplexToComplexFFTImageFilter3DFloatTest (SEGFAULT)
        798 - itkVnlComplexToComplexFFTImageFilter2DDoubleTest (SEGFAULT)
        799 - itkVnlComplexToComplexFFTImageFilter3DDoubleTest (SEGFAULT)
        800 - itkFFTWComplexToComplexFFTImageFilter2DFloatTest (SEGFAULT)
        801 - itkFFTWComplexToComplexFFTImageFilter3DFloatTest (SEGFAULT)
        802 - itkFFTWComplexToComplexFFTImageFilter2DDoubleTest (SEGFAULT)
        803 - itkFFTWComplexToComplexFFTImageFilter3DDoubleTest (SEGFAULT)
        923 - itkDCMTKImageIOMultiFrameImageTest (Failed)
        1153 - itkMetaImageIOTest2 (SEGFAULT)
        1438 - FrequencyIterators.Even3D (Failed)
        1439 - FrequencyIterators.Even2D (Failed)
        1440 - FrequencyIterators.Odd3D (Failed)
        1441 - FrequencyIterators.Odd2D (Failed)
        2862 - FFTDirectInverse2Test (Failed)
```

**Comment by imikejackson** [comment] 2019-08-15 20:40
@dzenanz We can't simply change the order of loading because ONLY the first plugin that uses ITK will have filters that work. The other 3 plugins will have filters that stop working. So I need to find another way of fixing this. We may have to introduce an "ITKSupport" library just above SIMPLib but below the plugins in the hierarchy.

**Comment by imikejackson** [comment] 2019-08-15 21:07
@dzenanz The other issue is that clearly something got moved in ITK 5 versus ITK 4 since this same exact code base. I doubt that we will be able to figure out that subtle change. 

I was able to create a Private Filter in SIMPLib/CoreFilters that does the image reading but I'm not thrilled about having to now link SIMPLib to most of ITK.

**Comment by imikejackson** [comment] 2019-09-09 20:47
@dzenanz The branch topic/itk-symbol-loading for DREAM3D, SIMPL and ITKImageProcessing have all the fixes.

**Comment by dzenanz** [comment] 2019-09-09 21:00
Is `topic/itk-symbol-loading` in your forks? I don't see it in normal locations.

**Comment by imikejackson** [comment] 2019-11-15 19:38
Closing because the underlying issue was solved in the SIMPL repository and source codes. Those changes have been merged into develop branch

**Closed as completed by imikejackson** 2019-11-15 19:38 UTC
